### PR TITLE
Do not automatically delete workflow on error

### PR DESCRIPTION
**Pull request by rick-a-lane-ii**
Avoid deleting the workflow if creating the revision fails.

By far, the most common reasons for errors during revision processing are validation errors.
This shouldn't result in deletion of the workflow.

In the future, as we improve our validation, this could potentially provide more helpful commentary/instructions regarding fixing the workflow file and replacing the file.

Even then, deleting the workflow for any other reason would and should never be done automatically here. A destructive act of that nature could only be considered as an optional flag that has to be explicitly set.

### CODE REVIEW

**Comment by impl** [comment]
Doesn't this only apply on workflow creation? I don't see the same logic in the `replace` subcommand where it would seem definitively wrong. It feels OK for this behavior to exist in `add` although I'm not sure I have a super strong opinion about it.

**Comment by rick-a-lane-ii** [comment]
Only on workflow creation.
It's not even remotely acceptable behavior.

**Comment by rick-a-lane-ii** [comment]
1.) In any case where you provide the ability for a user to create and delete an entity, it is generally ill-advised to make meaningful judgment calls about when to automatically delete based on errors (or any other factors). It takes away user control of something you've provided them in the first place.

**Comment by impl** [comment]
Can you clarify why you feel that way, e.g., what use case would we be solving for here? The UX we present (I thought, anyway) is that from the CLI perspective there's a 1-1 correspondence between the workflow itself and the initial revision. I'm not opposed to changing it, but I feel like we could probably improve the messaging. For example, for `-f` we should make it explicit that it's an initial revision and not "the workflow file", and when it fails to create we should give the user a message like "Your workflow XYZ was created, but the revision itself could not be because <errors>. You can try to upload a new revision with `relay workflow replace ...`"

**Comment by rick-a-lane-ii** [comment]
2.) Compressing two discreet points of functionality into one command in a non-transactional way is going to cause potential issues regardless. And specifically in this case, a failure in creating a revision is not a failure in creating a workflow. Deleting the entire workflow is a destructive act without any logic behind it.

**Comment by rick-a-lane-ii** [comment]
3.) The Relay CLI is providing a different view of what a "workflow" is. This does not sync with the UI. Anyone familiar with the UI would not expect a workflow to be deleted if the file is invalid.

**Comment by rick-a-lane-ii** [comment]
4.) A workflow is not a workflow file.

**Comment by rick-a-lane-ii** [comment]
5.) If we want a workflow to be a workflow file, that would require a systemic change to the UI.

**Comment by rick-a-lane-ii** [comment]
6.) The Relay UI does not delete a workflow if the file/revision is invalid.

**Comment by rick-a-lane-ii** [comment]
7.) We already have some elements attached to a "workflow" that separate it from simply representing a file. This will likely continue. I don't see a path forward where we don't continue to expand the complexity of a workflow.

**Comment by rick-a-lane-ii** [comment]
8.) All commands that work against the workflow without the presence of a file or the requirement of a file should reasonably be considered to work after a workflow has been created, regardless of whether the file is valid.

**Comment by impl** [comment]
Makes sense. I'd loop in @ahpook here as well. So my suggestions would be:

For `workflow add`:
- Remove the automatic deletion on failure (as you've done here)
- Make `-f` optional
- Clarify (in user-facing docs/messaging) that `-f` is the initial workflow revision content, not "the workflow file"
- Update error messages to distinguish between the revision and the workflow itself

For `workflow replace` / `workflow download` / etc.:
- Clarify (in user-facing docs/messaging) that it affects a revision of an existing workflow, not replaces the workflow itself

@ahpook, what do you think? This would better align the CLI behavior with the GUI.

**Comment by rick-a-lane-ii** [comment]
It's fairly easy to create a workflow via the CLI, start using it from the UI, only for it to delete it out from under you (as a user) with the way it works now. I've already had it corrupt the file/revision data on several cases as well.

If we really wanted to accomplish the same functionality, it would make more sense to validate the file first. And ideally in conjunction with providing the file as part of the initial request to prevent other issues. The latter would essentially be transactional in one way or another, which would achieve the same thing without other side effects.

But I wouldn't personally advocate for making the UX between the UI and the CLI drastically different in any case.

**Comment by rick-a-lane-ii** [comment]
But the larger concern I have is that once you create the workflow itself right now, it's going to invariably start creating other backend resources. It will be available to view and edit via the UI. It will be show up in workflow lists immediately. Secrets can be assigned.

This has potential impact to the user from a manual perspective, and in numerous possible was for automation, which may start functioning based on the presence of the workflow in a parallel manner.

**Comment by ahpook** [comment]
> Make -f optional

What would happen if you did workflow add but didn't supply a file...? 

> Clarify (in user-facing docs/messaging) that -f is the initial workflow revision content, not "the workflow file"

I'm not sure I'm completely clear on this distinction. I do think the original intent of this change is correct.

**Comment by impl** [comment]
> What would happen if you did workflow add but didn't supply a file...?

It would create the workflow without a revision (so running it would effectively be a no-op). This is what happens in the GUI right now -- you get a blank editor to start working on your workflow.

> I'm not sure I'm completely clear on this distinction. I do think the original intent of this change is correct.

This is mostly to clarify _why_ `-f` is optional: we need to make it clear that it's possible for a workflow to have no content at all until you give it some (which is why it's the initial content, if you so choose to specify it).

**Comment by rick-a-lane-ii** [comment]
I originally made the file optional as part of this change, and clarified the information presented slightly. But I decided against making that judgement call. And I'm not sure of the exact terminology here, i.e. "revision", "file", "code"?

But a specific use-case we'll likely want to support is independent automation that updates the file and secrets separately. In both cases, it should allow the ability to create the workflow if it doesn't exist (without erroring out because it already exists, even if this is an optional flag).

An automated process that updates secrets shouldn't be required to have access to the workflow file. Nor should it necessarily require a workflow to be created in advance, as that leads to fairly brittle processing. And it naturally must support a situation where the user periodically chooses to delete the workflow for one reason or another.

This requirement will likely increase as we add more complexity to the workflow (i.e. connections, environment configuration, etc.). Unless we plan on updating the workflow to solely reference external sources for this type of data, and rely on other commands or entities to update that respective data. Which is not necessarily a bad idea. We could make an argument for a more holistic workflow, but currently we're treating these as fundamental part of the workflow and enable these from Relay directly.

**Comment by rick-a-lane-ii** [comment]
I also did not want to divert the discussion from the system design issue at hand that needs to be fixed here.

**Comment by impl** [comment]
> I originally made the file optional as part of this change, and clarified the information presented slightly. But I decided against making that judgement call. And I'm not sure of the exact terminology here, i.e. "revision", "file", "code"?

I think that, if we're both in rough agreement on the file being optional, we should just say that such a call has been made and update the code to reflect that. I agree that the language could probably use another pass and that the existing terminology is confusing (especially since we don't directly expose revisions in the GUI), and I'd be happy to get this in, I think, with just the file-optional change being made, giving us pretty much exact parity with the GUI. We can make the language consistent in a follow-up PR.

**Review by impl — APPROVED** [review]
LGTM!

**Pull request merged**
